project:
  type: website
  output-dir: docs

website:
  title: "Frances Heitkemper"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: "Resume"
      - text: "Projects"
        menu:
        - text: "Love Island USA"
          href: LoveIslandUSA.qmd
        - text: "UK Baby Names"
          href: UKBabyNames.qmd
        - text: "European Parenting Leave Policies"
          href: Parenting.qmd
        - text: "R Package 'biwt'"
          href: https://hardin47.github.io/biwt/articles/biwt.html

format:
  html:
    theme:
      - morph
      - styles.scss
    toc: true
    page-layout: full
