project:
  type: website
  output-dir: docs

website:
  title: "Frances Heitkemper"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Projects"
        menu:
        - text: "UK Baby Names"
          href: UKBabyNames.qm