---
title: "Love Island USA"
author: "Frances Heitkemper"
date: July 23, 2026
format: 
  html:
    embed-resources: true
    code-fold: false
execute:
  warning: false
  message: false
---
The data I looked at this week is all the Love Island USA couples 
```{r}
library(tidyverse)
library(rvest)
library(jsonlite)
```

```{r}
url8 <- "https://en.wikipedia.org/wiki/Love_Island_USA_season_8"
url7 <- "https://en.wikipedia.org/wiki/Love_Island_USA_season_7"
url6 <- "https://en.wikipedia.org/wiki/Love_Island_USA_season_6"
url5 <- "https://en.wikipedia.org/wiki/Love_Island_USA_season_5"
url4 <- "https://en.wikipedia.org/wiki/Love_Island_USA_season_4"
url3 <- "https://en.wikipedia.org/wiki/Love_Island_USA_season_3"
url2 <- "https://en.wikipedia.org/wiki/Love_Island_USA_season_2"
url1 <- "https://en.wikipedia.org/wiki/Love_Island_USA_season_1"

extract_couples <- function(url) {
page <- read_html(url)
all_tables <- page |> html_elements("table.wikitable") # |> html_table()
coupling_table <- all_tables[[2]]

rows <- coupling_table |>
   html_element("tbody") |>
   html_elements("tr")

rows <- rows[-c(1, 2, length(rows)-c(0:6))]

names <- rows |>
   html_elements("th") |>
   html_text() |>
   str_trim()

extract_matches <- function(row) {
   row |>
     html_elements("td") |>
     html_text() |>
     str_trim()
 }

map(rows, extract_matches) |>
  map2(names, ~ tibble(x = .y, y = .x)) |>
  list_rbind() |>
  filter(!str_detect(y, "\\(")) |>
   filter(!str_detect(y, "\\)")) |>
   filter(!str_detect(y, "\\&")) |>
   filter(!str_detect(y, "save")) |>
   filter(!str_detect(y, "dump")) |>
   filter(!str_detect(y, "100")) |>
   filter(y != "N/A", y != "Not in Villa", y != "Single", y != "Safe", y != "Saved", y != "Finalist", y != "Vulnerable", y != "Eliminated", y != "Not inVilla", y != "Immune")
}
```
```{r}
li_data <- paste0("https://en.wikipedia.org/wiki/Love_Island_USA_season_", 1:8) |>
 map(extract_couples) |>
 list_rbind(names_to = "season") |>
 select(x, y, season)

write_csv(li_data,"data.csv")
```

Each node is a person on Love Island and Each line connects who was officaly coupled up at one point.
```{r}
library(ggraph)
library(tidygraph)
library(igraph)

chart_graph <- function(data) {
as_tbl_graph(data, directed = FALSE) |>
 ggraph(layout = "fr") +
   geom_edge_link() +
   geom_node_point() +
   geom_node_text(aes(label = name), repel = TRUE) +
   theme_graph() +
   theme(
     plot.background = element_rect(fill = "transparent", color = NA),
     panel.background = element_rect(fill = "transparent", color = NA)
) 
}
```

::: {.panel-tabset}
```{r}
#| label: graph-tabset
#| results: asis
#| dev.args: !expr list(bg = "transparent")

set.seed(1234)

for (season in sort(unique(li_data$season))) {
  cat("\n\n## Season", season, "\n\n")
  print(chart_graph(li_data[li_data$season == season, ]))
}
```
:::